#!/usr/bin/env bash
# shellcheck shell=bash

# Base system configuration writers.
#
# Expected variables (set by install.sh):
#   TARGET, HOSTNAME
#   ROOT_DEV, DATA_DEV, SWAP_DEV
#   P_BOOT, BOOT_MODE, P1
#   ROOT_FS, DATA_FS
#   MIRROR, RELEASE
#   HAS_SWAP
#
# Requires from other libs:
#   log(), die(), need_cmd()

config_components() {
  local components
  components="main contrib non-free"
  case "${RELEASE}" in
    bookworm|trixie|testing|sid)
      components="main contrib non-free non-free-firmware"
      ;;
  esac
  printf '%s' "$components"
}

config_write_base() {
  log "Writing base config (hostname, hosts, fstab, apt sources)..."

  mkdir -p "$TARGET/etc/apt"

  # hostname
  printf '%s\n' "$HOSTNAME" >"$TARGET/etc/hostname"

  # hosts
  cat >"$TARGET/etc/hosts" <<EOF_HOSTS
127.0.0.1 localhost
127.0.1.1 $HOSTNAME

::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF_HOSTS

  # fstab UUIDs
  local uuid_root uuid_boot uuid_data uuid_efi uuid_swap
  uuid_root="$(blkid -s UUID -o value "$ROOT_DEV")"
  uuid_boot="$(blkid -s UUID -o value "$P_BOOT")"
  uuid_data="$(blkid -s UUID -o value "$DATA_DEV")"
  uuid_efi=""
  uuid_swap=""

  if [[ "$BOOT_MODE" == "uefi" ]]; then
    uuid_efi="$(blkid -s UUID -o value "$P1")"
  fi

  if [[ "${HAS_SWAP:-0}" == "1" ]]; then
    uuid_swap="$(blkid -s UUID -o value "$SWAP_DEV")"
  fi

  cat >"$TARGET/etc/fstab" <<EOF_FSTAB
UUID=$uuid_root  /           $ROOT_FS  defaults,noatime  0  1
UUID=$uuid_boot  /boot       ext4      defaults,noatime  0  2
UUID=$uuid_data  /var/lib/vz $DATA_FS  defaults,noatime  0  2
EOF_FSTAB

  if [[ "$BOOT_MODE" == "uefi" ]]; then
    cat >>"$TARGET/etc/fstab" <<EOF_EFI
UUID=$uuid_efi   /boot/efi   vfat      umask=0077       0  1
EOF_EFI
  fi

  if [[ "${HAS_SWAP:-0}" == "1" ]]; then
    cat >>"$TARGET/etc/fstab" <<EOF_SWAP
UUID=$uuid_swap  none        swap      sw              0  0
EOF_SWAP
  fi

  # sources.list
  local components
  components="$(config_components)"

  cat >"$TARGET/etc/apt/sources.list" <<EOF_APT
# Generated by debootstrap-installer

deb $MIRROR $RELEASE $components

deb $MIRROR $RELEASE-updates $components

deb http://security.debian.org/debian-security $RELEASE-security $components
EOF_APT
}
