#!/usr/bin/env bash
# shellcheck shell=bash

# Configure /etc/resolv.conf in chroot.
#
# Public:
#   exec_chroot_dns
#
# Requires variables:
#   TARGET_DIR
#   LOG_FILE
#
# Optional:
#   NET4_DNS
#   NET6_DNS
#   NET_FALLBACK_DNS
#   NET4_ENABLE
#   NET6_ENABLE

exec_chroot_dns() {
  : "${TARGET_DIR:?TARGET_DIR is required}"
  : "${LOG_FILE:?LOG_FILE is required}"

  exec_require_tools awk sed tr findmnt || return 1

  if ! findmnt -rn "${TARGET_DIR}" >/dev/null 2>&1; then
    log "[!] chroot_dns: TARGET_DIR is not mounted: ${TARGET_DIR}"
    ui_msg "Chroot DNS requires mounted TARGET_DIR:\n${TARGET_DIR}\nLog: ${LOG_FILE}"
    return 1
  fi

  exec_progress 0 "Preparing chroot DNS..."

  local dns_servers=""
  local host_dns=""
  local domain=""
  local search=""
  local target_resolv="${TARGET_DIR}/etc/resolv.conf"

  if [[ -n "${NET4_DNS:-}" ]]; then
    dns_servers+="${NET4_DNS}"
  fi
  if [[ -n "${NET6_DNS:-}" ]]; then
    [[ -n "$dns_servers" ]] && dns_servers+=" "
    dns_servers+="${NET6_DNS}"
  fi

  if [[ -f /etc/resolv.conf ]]; then
    host_dns="$(awk '/^nameserver[[:space:]]+/{print $2}' /etc/resolv.conf 2>/dev/null | tr '\n' ' ' | sed -E 's/[[:space:]]+$//')"
    domain="$(awk '/^domain[[:space:]]+/{print $2; exit}' /etc/resolv.conf 2>/dev/null)"
    search="$(awk '/^search[[:space:]]+/{for(i=2;i<=NF;i++){printf (i==2?"%s":" %s"),$i} print ""; exit}' /etc/resolv.conf 2>/dev/null)"
  fi

  if [[ -z "$dns_servers" ]]; then
    dns_servers="$host_dns"
  fi

  if [[ -z "$dns_servers" ]]; then
    if [[ -n "${NET_FALLBACK_DNS:-}" ]]; then
      dns_servers="${NET_FALLBACK_DNS}"
    else
      if [[ "${NET6_ENABLE:-0}" == "1" && "${NET4_ENABLE:-1}" != "1" ]]; then
        dns_servers="2606:4700:4700::1111 2001:4860:4860::8888"
      elif [[ "${NET6_ENABLE:-0}" == "1" && "${NET4_ENABLE:-1}" == "1" ]]; then
        dns_servers="1.1.1.1 8.8.8.8 2606:4700:4700::1111 2001:4860:4860::8888"
      else
        dns_servers="1.1.1.1 8.8.8.8"
      fi
    fi
  fi

  if [[ -z "$dns_servers" ]]; then
    log "[!] chroot_dns: no DNS servers found"
    ui_msg "Failed to determine DNS servers for chroot.\nLog: ${LOG_FILE}"
    return 1
  fi

  exec_progress 60 "Writing ${target_resolv}..."
  {
    echo "# Generated by Debian-ReInstall (chroot DNS)"
    [[ -n "$domain" ]] && echo "domain $domain"
    [[ -n "$search" ]] && echo "search $search"
    local ns
    for ns in $dns_servers; do
      echo "nameserver $ns"
    done
  } >"${target_resolv}"

  exec_progress 90 "Chroot DNS configured."
  log "[=] chroot_dns: OK target=${TARGET_DIR} resolv=${target_resolv}"
  return 0
}
