#!/usr/bin/env bash
# shellcheck shell=bash

# Writes network config inside target:
# - NET_STACK=networkd|ifupdown
# - NET_IFACE
# - NET4_ENABLE (0/1), NET4_MODE=dhcp|static, NET4_ADDR (CIDR), NET4_GW, NET4_DNS
# - NET6_ENABLE (0/1), NET6_MODE=dhcp|static, NET6_ADDR (CIDR), NET6_GW, NET6_DNS
# - NET_FALLBACK_DNS (optional)
#
# Depends:
# - exec_in_chroot() from 07-chroot_mounts.sh

: "${DEFAULT_PUBLIC_DNS:=1.1.1.1 8.8.8.8}"

exec_network_configure() {
  : "${TARGET_DIR:?}"
  : "${LOG_FILE:?}"
  : "${NET_STACK:?}"
  : "${NET_IFACE:?}"

  exec_require_tools mkdir cat rm ln chmod || return 1

  case "${NET_STACK}" in
    networkd) exec_network_write_networkd ;;
    ifupdown) exec_network_write_ifupdown ;;
    *)
      ui_msg "Unknown NET_STACK=${NET_STACK}\nLog: ${LOG_FILE}"
      return 1
      ;;
  esac
}

exec_network_write_networkd() {
  exec_progress 0 "Writing systemd-networkd config..."

  mkdir -p "${TARGET_DIR}/etc/systemd/network" || true

  local f="${TARGET_DIR}/etc/systemd/network/10-${NET_IFACE}.network"
  local dns; dns="$(exec_network_pick_dns)"

  {
    echo "[Match]"
    echo "Name=${NET_IFACE}"
    echo
    echo "[Network]"

    # DHCP matrix
    if (( NET4_ENABLE == 1 )) && [[ "${NET4_MODE}" == "dhcp" ]] && (( NET6_ENABLE == 1 )) && [[ "${NET6_MODE}" == "dhcp" ]]; then
      echo "DHCP=yes"
      echo "IPv6AcceptRA=yes"
    else
      if (( NET4_ENABLE == 1 )) && [[ "${NET4_MODE}" == "dhcp" ]]; then
        echo "DHCP=ipv4"
      fi
      if (( NET6_ENABLE == 1 )) && [[ "${NET6_MODE}" == "dhcp" ]]; then
        echo "DHCP=ipv6"
        echo "IPv6AcceptRA=yes"
      else
        echo "IPv6AcceptRA=no"
      fi
    fi

    # Static v4
    if (( NET4_ENABLE == 1 )) && [[ "${NET4_MODE}" == "static" ]]; then
      echo "Address=${NET4_ADDR}"
      [[ -n "${NET4_GW:-}" ]] && echo "Gateway=${NET4_GW}"
    fi

    # Static v6
    if (( NET6_ENABLE == 1 )) && [[ "${NET6_MODE}" == "static" ]]; then
      echo "Address=${NET6_ADDR}"
      [[ -n "${NET6_GW:-}" ]] && echo "Gateway=${NET6_GW}"
      echo "IPv6AcceptRA=no"
    fi

    # DNS
    if [[ -n "${dns}" ]]; then
      local ip
      for ip in ${dns}; do
        echo "DNS=${ip}"
      done
    fi
  } >"$f"

  exec_progress 60 "Enabling networkd/resolved (best-effort)..."
  exec_try exec_in_chroot systemctl disable networking
  exec_try exec_in_chroot systemctl enable systemd-networkd
  exec_try exec_in_chroot systemctl enable systemd-resolved

  # resolved-managed resolv.conf
  exec_progress 85 "Setting resolv.conf symlink for systemd-resolved..."
  exec_try exec_in_chroot rm -f /etc/resolv.conf
  exec_try exec_in_chroot ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf

  exec_progress 100 "Network (networkd) configured."
  return 0
}

exec_network_write_ifupdown() {
  exec_progress 0 "Writing ifupdown interfaces..."

  mkdir -p "${TARGET_DIR}/etc/network" || true

  local f="${TARGET_DIR}/etc/network/interfaces"
  local dns; dns="$(exec_network_pick_dns)"

  {
    echo "# Generated by installer"
    echo "auto lo"
    echo "iface lo inet loopback"
    echo
    echo "allow-hotplug ${NET_IFACE}"

    # IPv4
    if (( NET4_ENABLE == 1 )); then
      if [[ "${NET4_MODE}" == "dhcp" ]]; then
        echo "iface ${NET_IFACE} inet dhcp"
      else
        echo "iface ${NET_IFACE} inet static"
        echo "  address ${NET4_ADDR}"
        [[ -n "${NET4_GW:-}" ]] && echo "  gateway ${NET4_GW}"
        [[ -n "${dns}" ]] && echo "  dns-nameservers ${dns}"
      fi
    else
      echo "iface ${NET_IFACE} inet manual"
    fi

    echo

    # IPv6
    if (( NET6_ENABLE == 1 )); then
      if [[ "${NET6_MODE}" == "dhcp" ]]; then
        echo "iface ${NET_IFACE} inet6 dhcp"
      else
        echo "iface ${NET_IFACE} inet6 static"
        echo "  address ${NET6_ADDR}"
        [[ -n "${NET6_GW:-}" ]] && echo "  gateway ${NET6_GW}"
      fi
    else
      echo "iface ${NET_IFACE} inet6 manual"
    fi
  } >"$f"

  exec_progress 65 "Writing plain resolv.conf..."
  exec_network_write_resolv_conf_plain "${dns}"

  exec_progress 85 "Enabling networking (best-effort)..."
  exec_try exec_in_chroot systemctl disable systemd-networkd
  exec_try exec_in_chroot systemctl disable systemd-resolved
  exec_try exec_in_chroot systemctl enable networking

  exec_progress 100 "Network (ifupdown) configured."
  return 0
}

exec_network_pick_dns() {
  local dns=""

  [[ -n "${NET4_DNS:-}" ]] && dns="${NET4_DNS}"
  [[ -n "${NET6_DNS:-}" ]] && dns="${dns} ${NET6_DNS}"

  dns="$(echo "${dns}" | awk '{$1=$1;print}')"

  if [[ -z "${dns}" ]]; then
    if [[ -n "${NET_FALLBACK_DNS:-}" ]]; then
      dns="${NET_FALLBACK_DNS}"
    else
      dns="${DEFAULT_PUBLIC_DNS}"
    fi
  fi

  echo "${dns}" | awk '{$1=$1;print}'
}

exec_network_write_resolv_conf_plain() {
  local dns="$1"
  local target_rc="${TARGET_DIR}/etc/resolv.conf"

  mkdir -p "${TARGET_DIR}/etc" || true
  [[ -L "$target_rc" ]] && rm -f "$target_rc"

  {
    local ip
    for ip in ${dns}; do
      echo "nameserver ${ip}"
    done
  } >"$target_rc"

  chmod 644 "$target_rc" 2>/dev/null || true
  return 0
}
